### ISSUE TITLE
Allow configuration of the model to use in resources file

### ISSUE THREAD

**Issue by cknoxrun** [typus/typus#379]
It would be great to allow the specification of the model to use in the YAML configuration file for a resource. In my application, I want to have 2 forms for a single model. So a user would enter in the first page of information about a GameProduct for instance, and then go on to a second page with extra fields. In this case it would be great to have this type of configuration:

``` yaml
GameProduct:
  fields:
    default: title, genres, platforms, release_date
    form: title, box_art, long_desc, release_date, url, esrb, requirements, short_desc, fee, genres, developers, platforms
  application: Application
  search: title
  filters: genres, platforms, release_date
  order_by: -created_at, title
```

and a second configuration file (called game_product_extra.yml):

```
GameProductExtra:
  model: GameProduct
  fields:
    form: extra_description, rating
  relationships: media_assets, affiliate_links, game_publishers
  application: Application
```

Thoughts? I can start working on this if you think it would be a worthwhile addition.
